packages:
  - apps/*
  - packages/*
  - tools/*
  - tests

catalogMode: manual

catalog:
  '@dymo-api/better-auth': ^1.2.33
  '@types/node': ^24
  '@xcvzlabs/env': ^0.1.2
  better-auth: ^1.7.2
  drizzle-orm: 1.0.0-rc.4
  handlebars: ^4.7.9
  typescript: ^6.0.3
  unemail: ^0.5.0
  uuid: ^14.0.2
  valibot: ^1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0

overrides:
  vite: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: '*'

allowBuilds:
  esbuild: true
  vue-demi: true
